# Generated by Django 5.1.2 on 2024-11-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
