# Generated by Django 5.1.2 on 2024-11-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время"),
        ),
    ]
